# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

automation manual: !include_dir_merge_named /config/custom/automations/
automation ui: !include automations.yaml
script manual: !include_dir_merge_named /config/custom/scripts/
script ui: !include scripts.yaml
scene manual: !include_dir_merge_named /config/custom/scenes/
scene ui: !include scenes.yaml
light manual: !include_dir_merge_named /config/custom/lights/
light ui: !include lights.yaml
sensor: !include sensors.yaml
template: !include template.yaml
rest: !include rest.yaml
multiscrape: !include multiscrape.yaml
openhasp: !include_dir_merge_named /config/openhasp_configs/
#group manual: !include_dir_merge_named /config/custom/group/
homeassistant:
  customize: !include_dir_merge_named /config/custom/misc/
  allowlist_external_dirs:
    - "/tmp/"
    - "/config/blink/images/"
    - "/config/openhasp"
  packages: !include_dir_named integrations

modbus:
  - name: trovis
    type: !secret trovis_connection_type
    host: !secret trovis_ip
    port: !secret trovis_port
    sensors: !include_dir_merge_list trovis557x/registers/
    binary_sensors: !include_dir_merge_list trovis557x/coils/
    message_wait_milliseconds: 30
    timeout: 10
    delay: 5
